// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Sentence             string   `protobuf:"bytes,2,opt,name=sentence,proto3" json:"sentence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *HelloResponse) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

type GuessNumberResponse struct {
	IsSuccess            bool                 `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	UserRegions          []int32              `protobuf:"varint,2,rep,packed,name=userRegions,proto3" json:"userRegions,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GuessNumberResponse) Reset()         { *m = GuessNumberResponse{} }
func (m *GuessNumberResponse) String() string { return proto.CompactTextString(m) }
func (*GuessNumberResponse) ProtoMessage()    {}
func (*GuessNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *GuessNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuessNumberResponse.Unmarshal(m, b)
}
func (m *GuessNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuessNumberResponse.Marshal(b, m, deterministic)
}
func (m *GuessNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuessNumberResponse.Merge(m, src)
}
func (m *GuessNumberResponse) XXX_Size() int {
	return xxx_messageInfo_GuessNumberResponse.Size(m)
}
func (m *GuessNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GuessNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GuessNumberResponse proto.InternalMessageInfo

func (m *GuessNumberResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *GuessNumberResponse) GetUserRegions() []int32 {
	if m != nil {
		return m.UserRegions
	}
	return nil
}

func (m *GuessNumberResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*GuessNumberResponse)(nil), "GuessNumberResponse")
}

func init() {
	proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47)
}

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4d, 0x4b, 0xf3, 0x40,
	0x14, 0x85, 0xdf, 0xb4, 0x7d, 0x4b, 0x7a, 0x6b, 0xbb, 0x18, 0x41, 0x42, 0x14, 0x0c, 0x59, 0x15,
	0x0a, 0x53, 0xa8, 0x0b, 0xd7, 0x2d, 0x88, 0xba, 0x91, 0x92, 0xb8, 0x72, 0x97, 0xc4, 0x6b, 0x88,
	0x64, 0x3e, 0xcc, 0x9d, 0x59, 0xf4, 0x07, 0xf8, 0xbf, 0x25, 0x63, 0xaa, 0xd1, 0x6e, 0xdc, 0xdd,
	0x8f, 0x73, 0xcf, 0xcc, 0x73, 0x60, 0x92, 0x69, 0xcd, 0x75, 0xa3, 0x8c, 0x0a, 0xcf, 0x4b, 0xa5,
	0xca, 0x1a, 0x57, 0xae, 0xcb, 0xed, 0xcb, 0x0a, 0x85, 0x36, 0xfb, 0x6e, 0x79, 0xf9, 0x7b, 0x69,
	0x2a, 0x81, 0x64, 0x32, 0xd1, 0x5d, 0xc7, 0x31, 0x9c, 0xdc, 0x61, 0x5d, 0xab, 0x04, 0xdf, 0x2c,
	0x92, 0x61, 0x0c, 0x46, 0x32, 0x13, 0x18, 0x78, 0x91, 0xb7, 0x98, 0x24, 0xae, 0x8e, 0xef, 0x61,
	0xd6, 0x69, 0x48, 0x2b, 0x49, 0xc8, 0x2e, 0x60, 0x52, 0x51, 0x6a, 0x8b, 0x02, 0x89, 0x9c, 0xd2,
	0x4f, 0xbe, 0x07, 0x2c, 0x04, 0x9f, 0x50, 0x1a, 0x94, 0x05, 0x06, 0x03, 0x67, 0xf3, 0xd5, 0xc7,
	0xef, 0x1e, 0x9c, 0xde, 0x5a, 0x24, 0x7a, 0xb0, 0x22, 0xc7, 0xe6, 0x8f, 0x8e, 0x11, 0x4c, 0x2d,
	0xb5, 0xea, 0xb2, 0x52, 0x92, 0x82, 0x41, 0x34, 0x5c, 0xfc, 0x4f, 0xfa, 0x23, 0xc6, 0x61, 0xd4,
	0x92, 0x05, 0xc3, 0xc8, 0x5b, 0x4c, 0xd7, 0x21, 0xff, 0xc4, 0xe6, 0x07, 0x6c, 0xfe, 0x78, 0xc0,
	0x4e, 0x9c, 0x6e, 0x2d, 0x61, 0xbc, 0xd1, 0x7a, 0xa3, 0x2b, 0xb6, 0x04, 0x3f, 0xcd, 0xf6, 0x8e,
	0x8f, 0xcd, 0x78, 0x3f, 0x8b, 0x70, 0xce, 0x7f, 0x60, 0xc7, 0xff, 0xd8, 0x35, 0x4c, 0x7b, 0xbf,
	0x67, 0x67, 0x47, 0xef, 0xdc, 0xb4, 0xd9, 0x1f, 0x1f, 0x6e, 0x97, 0x30, 0x2f, 0x94, 0xe0, 0x94,
	0x09, 0x5d, 0x23, 0x2f, 0x51, 0x6e, 0x67, 0xa9, 0xab, 0x77, 0x8d, 0x7a, 0xc5, 0xc2, 0xec, 0xbc,
	0x27, 0x9f, 0xaf, 0x84, 0x7a, 0xc6, 0x9a, 0xf2, 0xb1, 0xb3, 0xbb, 0xfa, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xd7, 0x72, 0x69, 0x7d, 0xe5, 0x01, 0x00, 0x00,
}
